pipeline {
    agent any

    options {
        timestamps()
    }

    environment {
        APP_DIR   = 'DevOps-Project-33/DevSecOps-CI-CD-Pipeline'
        IMAGE_NAME = 'project33-jpetstore'
    }

    stages {

        stage('Environment Check') {
            steps {
                sh '''
                    echo "===== Java ====="
                    java -version

                    echo "===== Maven ====="
                    mvn -version

                    echo "===== Docker ====="
                    docker --version

                    echo "===== Trivy ====="
                    trivy --version
                '''
            }
        }

        stage('Compile') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn -B clean compile'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn -B test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir("${APP_DIR}") {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn -B \
                              org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                              -Dsonar.projectKey=project33-jpetstore \
                              -Dsonar.projectName=Project33-JPetStore
                        '''
                    }
                }
            }
        }

        stage('SonarQube Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Package WAR') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        mvn -B package -DskipTests
                        ls -lh target/jpetstore.war
                    '''
                }
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dir("${APP_DIR}") {
                    dependencyCheck(
                        odcInstallation: 'dependency-check',
                        additionalArguments: '''
                            --scan .
                            --format XML
                            --prettyPrint
                        '''
                    )
                }
            }

            post {
                always {
                    dependencyCheckPublisher(
                        pattern: '**/dependency-check-report.xml'
                    )
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        docker build \
                          -t ${IMAGE_NAME}:${BUILD_NUMBER} .

                        docker image inspect \
                          ${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
       }


stage('Trivy Image Scan') {
    steps {
        dir("${APP_DIR}") {
            sh '''
                trivy image \
                  --scanners vuln \
                  --timeout 20m \
                  --severity HIGH,CRITICAL \
                  --ignore-unfixed \
                  --exit-code 0 \
                  --format table \
                  --output trivy-image.txt \
                  ${IMAGE_NAME}:${BUILD_NUMBER}

                echo "===== Trivy Report ====="
                cat trivy-image.txt
            '''
        }
    }
}
        }
    }
}
